AvivaTestMVC/AvivaTestMVC/Models/AvivaTest.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvivaTestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvivaTest
    {
        public int ID { get; set; }
        public int EnteredNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}

AvivaTestMVC/AvivaTestMVC/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvivaTestMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestVijayEntities1 : DbContext
    {
        public TestVijayEntities1()
            : base("name=TestVijayEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AvivaTest> AvivaTests { get; set; }
    }
}

AvivaTestMVC/AvivaTestMVC/Models/Model1.Designer.cs
// Default code generation is disabled for model 'c:\users\vijaykbabu\documents\visual studio 2012\Projects\AvivaTestMVC\AvivaTestMVC\Models\Model1.edmx'. 
// To enable default code generation, change the value of the 'Code Generation Strategy' designer
// property to an alternate value. This property is available in the Properties Window when the model is
// open in the designer.

AvivaTestMVC/AvivaTestMVC/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

AvivaTestMVC/AvivaTestMVC/Controllers/AvivaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AvivaTestMVC.Models;
using AvivaTestMVC.ViewModel;

namespace AvivaTestMVC.Controllers
{
    public class AvivaController : Controller
    {
        //
        // GET: /Aviva/

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.DoneBy = "Vijay Babu";
            return View();
        }

        [HttpPost]
        public ActionResult Index(IndexViewModel objtestData, string direction)
        {
            if (ModelState.IsValid)
            {
                objtestData.CreatedDate = System.DateTime.Now;

                List<int> objnolist = new List<int>();
                if (direction == "Submit")
                {
                    //  Save number to DB
                    AvivaTest objavi = new AvivaTest();
                    objavi.EnteredNumber = objtestData.EnteredNumber;
                    objavi.CreatedDate = System.DateTime.Now;

                    TestVijayEntities1 objDbContext = new TestVijayEntities1();
                    objDbContext.AvivaTests.Add(objavi);
                    objDbContext.SaveChanges();

                    // Show only first 20 numbers
                    objtestData.PagingStart = 1;
                    if (objtestData.EnteredNumber > 20)
                    {
                        objtestData.PagingEnd = 20;
                        objtestData.Next = true;
                        objtestData.Previous = false;
                    }
                    else
                    {
                        objtestData.PagingEnd = objtestData.EnteredNumber;
                        objtestData.Next = false;
                        objtestData.Previous = false;
                    }
                }

                if (direction == "Next")  // On Next 
                {
                    objtestData.PagingStart = objtestData.PagingEnd + 1;
                    if (objtestData.PagingEnd + 20 < objtestData.EnteredNumber)
                    {
                        objtestData.PagingEnd = objtestData.PagingEnd + 20;
                        objtestData.Next = true;
                        objtestData.Previous = true;
                    }
                    else
                    {
                        objtestData.PagingEnd = objtestData.EnteredNumber;
                        objtestData.Next = false;
                        objtestData.Previous = true;
                    }
                }

                if (direction == "Previous")  //On Previous 
                {
                    objtestData.PagingEnd = objtestData.PagingStart -1 ;
                    if (objtestData.PagingEnd - 20 >0)
                    {
                        objtestData.PagingStart = objtestData.PagingStart - 20;
                        objtestData.Next = true;
                        objtestData.Previous = true;
                    }
                    else
                    {
                        objtestData.PagingStart = 1;
                        objtestData.Next = true;
                        objtestData.Previous = false;
                    }
                }

                for (int i = objtestData.PagingStart; i <= objtestData.PagingEnd; i++)
                {
                    objnolist.Add(i);
                }

                objtestData.NumberList = objnolist;

                ModelState.Clear();
                return View(objtestData);
            }
            else
            {
                ModelState.Clear();
                return View(objtestData);
            }
        }

    }
}

AvivaTestMVC/AvivaTestMVC/Views/Aviva/Index.cshtml
@model AvivaTestMVC.ViewModel.IndexViewModel
@{
    ViewBag.Title = "Index";
}
<script type="text/javascript" src="~/Scripts/jquery-1.7.1.js"></script>
<link href="~/Content/Site.css" rel="stylesheet" />
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}


@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset style="padding-left: 100Px;">
        <legend>
            <h2>Aviva Test Application  - @ViewBag.DoneBy</h2>
        </legend>
        <table>
            <tr>
                <td>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.EnteredNumber)
                    </div>
                </td>
                <td>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.EnteredNumber)
                        @Html.ValidationMessageFor(model => model.EnteredNumber)
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
            </tr>
        </table>
        <p style="padding-left: 100Px;">
            <input type="submit" value="Submit" name="direction" />
        </p>
    </fieldset>
    if (Model != null)
    {
    <fieldset>
        <legend>
            <h2>Result</h2>
        </legend>
        <table>
            @foreach (int i in Model.NumberList)
            {
                <tr>
                    <td>
                        @if (i % 3 == 0 && i % 5 == 0)
                        {
                            @Html.Label("fizz buzz")
                        }
                        else if (i % 3 == 0)
                        {
                            if (System.DateTime.Now.DayOfWeek == DayOfWeek.Wednesday)
                            {
                            <div class="font-Blue">
                                @Html.Label("Wizz")
                            </div>
                            }
                            else
                            {
                            <div class="font-Blue">
                                @Html.Label("fizz")
                            </div>
                            }

                        }
                        else if (i % 5 == 0)
                        {
                            if (System.DateTime.Now.DayOfWeek == DayOfWeek.Wednesday)
                            {
                            <div class="font-Green">
                                @Html.Label("buzz")
                            </div>
                            }
                            else
                            {
                            <div class="font-Green">
                                @Html.Label("buzz")
                            </div>
                            }
                        }
                        else
                        {
                            @Html.Label(i.ToString())
                        }
                    </td>
                </tr>   
            }
            <tr>
                <td>
                    @Html.HiddenFor(model => model.PagingStart)
                    @Html.HiddenFor(model => model.PagingEnd)
                    @*@Html.ActionLink("Next","Index","Aviva",new{Model.PagingNumber},null)*@
                </td>
            </tr>
            <tr>
                <td>
                    @if (Model.Next == true)
                    {
                        <input type="submit" value="Next" name="direction" />
                    }
                </td>
                <td>
                    @if (Model.Previous == true)
                    {
                        <input type="submit" value="Previous" name="direction" />
                    }
                </td>
            </tr>
        </table>

    </fieldset>
    }
}

AvivaTestMVC/AvivaTestMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>